.TH SVP "1" "February 2019" "svp 0.0.1" "User Commands"
.SH NAME
svp \- create and manage merge proposals
.SH DESCRIPTION
usage: svp [\-h] [\-\-version] {autopropose,hosters,login,proposals} ...
.SS "COMMAND OVERVIEW"
.TP
.B svp autopropose
Create a merge proposal.
.TP
.B svp hosters
Display known hosting sites.
.TP
.B svp login BASE-URL
Log into a new hosting site.
.TP
.B svp proposals [--status=open|close|merged]
Print URLs of all proposals of a specified status.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-version\fR
show program's version number and exit
.SH "SEE ALSO"
\&\fIdebian-svp\fR\|(1)
.SH AUTHORS
Jelmer Vernooij <jelmer@jelmer.uk>
