[package]
name = "svp-client"
version = "0.1.0"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
license = "Apache-2.0"
description = "Client for the silver-platter protocol"

[lib]

[dependencies]
log = "0.4.20"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.117"
