name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install devscripts libapt-pkg-dev libtdb-dev libssl-dev pkg-config nettle-dev clang
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools_rust setuptools
      - name: Install breezy
        run: python -m pip install --upgrade breezy
      - name: Build
        run: cargo build --verbose
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (no features)
        run: cargo test --no-default-features
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (cli, no debian)
        run: cargo test --no-default-features --features cli
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (debian, no cli)
        run: cargo test --no-default-features --features debian
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (default features)
        run: cargo test
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (all features)
        run: cargo test --all-features
        env:
          RUSTFLAGS: -Dwarnings
      - name: Check formatting
        run: cargo fmt -- --check
